name: blink
channels:
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - jupyter
  - matplotlib
  - matchms
  - networkx
  - pymzml
  - pyteomics
  - pip:
      - torch